all:
	g++ -Wall -pedantic -g -std=c++11 -o infinite_50000 infinite_50000.cpp
	g++ -Wall -pedantic -g -std=c++11 -o infinite infinite.cpp
	g++ -Wall -pedantic -g -std=c++11 -o run_time_stack_memory run_time_stack_memory.cpp
	g++ -Wall -pedantic -g -std=c++11 -o heap heap.cpp
	g++ -Wall -pedantic -g -std=c++11 -o collision collision.cpp

clean:
	rm -f infinite infinite_5000 run_time_stack_memory heap collision
