all: list_stack_queue list_stack_queue.bad_indentation person_student_employee pure_virtual1 pure_virtual3 pure_virtual4 x pure_virtual2

#item_cart:
#	g++ -Wall -pedantic -g -o item_cart item_cart.cpp

list_stack_queue.bad_indentation:
	g++ -Wall -pedantic -g -o list_stack_queue.bad_indentation list_stack_queue.bad_indentation.cpp

list_stack_queue:
	g++ -Wall -pedantic -g -o list_stack_queue list_stack_queue.cpp

person_student_employee:
	g++ -Wall -pedantic -g -o person_student_employee person_student_employee.cpp

pure_virtual1:
	g++ -Wall -pedantic -g -o pure_virtual1 pure_virtual1.cpp

pure_virtual2:
	g++ -Wall -pedantic -g -o pure_virtual2 pure_virtual2.cpp

pure_virtual3:
	g++ -Wall -pedantic -g -o pure_virtual3 pure_virtual3.cpp

pure_virtual4:
	g++ -Wall -pedantic -g -o pure_virtual4 pure_virtual4.cpp

x:
	g++ -Wall -pedantic -g -o x x.cpp

clean:
	rm item_cart list_stack_queue.bad_indentation list_stack_queue
	rm person_student_employee
	rm pure_virtual1 pure_virtual3 pure_virtual4
	rm x
